  version: '3.8'
services:
   postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
   shape:
     image: neridan/shape:latest
     container_name: shape
     ports:
       - "8080:8080"
     environment:
       - SPRING_PROFILES_ACTIVE=docker
     networks:
       - spring
       - postgres
     depends_on:
       - zipkin
       - postgres
       - rabbitmq
   fraud:
     image: neridan/fraud:latest
     container_name: fraud
     ports:
       - "8081:8081"
     environment:
       - SPRING_PROFILES_ACTIVE=docker
     networks:
       - spring
       - postgres
     depends_on:
       - zipkin
       - postgres
       - rabbitmq
   notification:
     image: neridan/notification:latest
     container_name: notification
     ports:
       - "8082:8082"
     environment:
       - SPRING_PROFILES_ACTIVE=docker
     networks:
       - spring
       - postgres
     depends_on:
       - zipkin
       - postgres
       - rabbitmq
   zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
   rabbitmq:
     image: rabbitmq:3.9.11-management-alpine
     container_name: rabbitmq
     ports:
       - "5672:5672"
       - "15672:15672"
     networks:
       - spring
#   eureka-server:
#     image: neridan/eureka-server:latest
#     container_name: eureka-server
#     ports:
#       - "8761:8761"
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker
#     networks:
#       - spring
#     depends_on:
#       - zipkin
#   apigw:
#     image: neridan/apigw:latest
#     container_name: apigw
#     ports:
#       - "8083:8083"
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker
#     networks:
#       - spring
#     depends_on:
#       - zipkin
#       - eureka-server
volumes:
  postgres:
    driver: local

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge